name: Tests execution

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: recipes_test
          MYSQL_USER: recipes
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 13306:3306
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Start mysql service
        run: sudo systemctl start mysql
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, mysql
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install PHP packages
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-suggest --optimize-autoloader

      - name: Prepare recipes app
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Install NODE
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: compile assets
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build

      - name: Filesystem permissions
        run: chmod a=rwx storage bootstrap/cache

      - name: Clear Laravel cache
        run: php artisan optimize:clear

      - name: Execute recipes tests
        run: php artisan test
